### ISSUE TITLE
how to install gpmp2

### ISSUE THREAD

**Issue by syx0629** [gtrll/gpmp2#28] opened 2019-05-17 02:57 UTC
Thank you for sharing your code.
when I install gpmp2,I make these mistakes:
```
user@505:~/code/gpmp2/gpmp2$ cmake -DGPMP2_BUILD_MATLAB_TOOLBOX:OPTION=ON -DGTSAM_TOOLBOX_INSTALL_PATH:PATH=/path/install/toolbox ..
CMake Error at /usr/share/cmake-3.5/Modules/CMakeFindDependencyMacro.cmake:45 (message):
  Invalid arguments to find_dependency
Call Stack (most recent call first):
  /usr/local/lib/cmake/GTSAM/GTSAMConfig.cmake:17 (find_dependency)
  CMakeLists.txt:27 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/user/code/gpmp2/gpmp2/CMakeFiles/CMakeOutput.log".
```
I don't know how to install gpmp2.please help me out

**Comment by mhmukadam** [comment] 2019-06-20 22:36
From the error message it looks like it cannot find GTSAM. Did you install all the dependencies?

Closing this issue for now as more info is needed to reproduce the error.

**Closed** 2019-06-20 22:37 UTC
